Revert r14846 - test suite regression
{{{
[ERROR]: xmantissa.test.test_website.WebSiteIntegrationTests.test_rootResource

Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/twisted/internet/defer.py", line 107, in maybeDeferred
    result = f(*args, **kw)
  File "/home/divmod/q-linux/q-linux/build/Nevow/nevow/guard.py", line 318, in locateChild
    return self._delegate(ctx, segments)
  File "/home/divmod/q-linux/q-linux/build/Nevow/nevow/guard.py", line 349, in _delegate
    rd = self.createSession(ctx, segments)
  File "/home/divmod/q-linux/q-linux/build/Nevow/nevow/guard.py", line 373, in createSession
    sz.fields = request.fields
exceptions.AttributeError: AccumulatingFakeRequest instance has no attribute fields
}}}